#设置该服务的端口
server:
  port: 8089

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yhl2574405253/config  #配置git所在的url
#          username:    配置git的用户名
#          password:    配置git的密码
